#本文件是全局配置
#具体可以填写哪些字段，需要看load.go是如何加载的
name: "Templete"
mode: "debug"       #模式
port: 8080          #端口
version: "v0.0.1"
start_time: "2024-01-25"
machine_id: 1

auth:
  jwt_expire: 8760   #jwt过期时间


#日志类配置
log:
  level: "info"           #日志级别
  filename: "shabi.log"   #日志文件名
  max_size: 200           #日志文件最大大小，单位是MB
  max_age: 30             #日志文件最大保存天数
  max_backups: 7          #最大备份文件数


#数据库配置
mysql:
  host: 127.0.0.1           #主机名
  port: 3306                #端口号
  user: "root"              #用户名
  password: "123456"        #密码
  dbname: "gin"             #数据库
  max_open_conns: 200       #最大连接数
  max_idle_conns: 50        #最大空闲连接数

#redis配置
redis:
  host: 127.0.0.1           #主机名
  port: 6379                #端口号
  password: ""              #密码
  db: 0                     #数据库
  pool_size: 100            #连接池大小
  
#其他配置
